import random 
import time
while True:
    panda=25
    kaplan=25
    print ("Panda vs Kaplan yarışmamıza hoşgeldiniz!")
    time.sleep(1)
    print ("Yarışmamız şöyle işlemektedir: İki oyuncu da 2 tane zar attıktan sonra çıkan sayılar toplanır ve iki oyuncununkilerinde karşılaştırılır.")
    print ("Karşılaştırıldıktan sonra kime daha çok sayı çıktıysa o kadar karşısındakine hasar verecektir.")
    time.sleep(9)
    print ("Bol şans!")
    while panda>0 and kaplan>0 :
        print ("Kaplan'ın canı: ", kaplan)
        time.sleep(1)
        print ("Panda'nın canı: ", panda)
        time.sleep(2)
        print ("Panda başlıyor!")
        time.sleep(1)
        input("Zar atmak için Enter'a basınız.")
        time.sleep(1)
        print ("1. zar atılıyor...")
        time.sleep(1)
        print (".")
        time.sleep(1)
        print (".")
        time.sleep(1)
        print (".")
        time.sleep(1)
        zar11=random.randint (1,6)
        print ("Birinci zardan ", zar11 ,"geldi!")
        time.sleep(1)
        input("Zar atmak icin Enter'a basiniz.")
        time.sleep(1)
        print ("2. zar atılıyor...")
        time.sleep(1)
        print (".")
        time.sleep(1)
        print (".") 
        time.sleep(1)
        print (".")
        time.sleep(1)
        zar12=random.randint (1,6)
        print ("2. zardan ", zar12,"geldi!")
        time.sleep(2)
        print ("Sıra Kaplan")
        time.sleep(1)
        input("Zar atmak icin Enter'a basiniz")
        time.sleep(1)
        print ("1. zar atiliyor")
        time.sleep(1)
        print (".")
        time.sleep(1)
        print (".")
        time.sleep(1)
        print (".")
        time.sleep(1)
        zar21=random.randint (1,6)
        print ("1. zardan ", zar21,"geldi")
        time.sleep(1)
        input("Zar atmak icin Enter'a basiniz")
        time.sleep(1)
        print ("2. zar atiliyor")
        time.sleep(1)
        print (".")
        time.sleep(1)
        print (".")
        time.sleep(1)
        print (".")
        time.sleep(1)
        zar22=random.randint (1,6)
        print ("2. zardan", zar22,"geldi")
        time.sleep(3)
        if zar11+zar12>zar21+zar22 :
            kaplan=kaplan-(zar11+zar12)
            print ("Bu turun kazanani Panda")
            time.sleep(3)
        elif zar21+zar22>zar11+zar12 :
            panda=panda-(zar21+zar22)
            print ("Bu turun kazanani Kaplan")
            time.sleep(3)
        else :
            print ("zarlar esit")
            time.sleep(3)
        if panda>0 and kaplan>0 :
            print ("siradaki tur")
            time.sleep(1)
    print ("Oyun bitti!")
    if panda<=0 :
        print ("kaplan kazandi!")
        time.sleep(2)
        print ("Puaniniz: ", kaplan)
        time.sleep(5)
    else :
        time.sleep(1)
        print ("Panda kazandi!")
        time.sleep(2)
        print ("Puaniniz: ", panda)
        time.sleep(5)